name: Deploy Flask App

on:
  push:
    branches:
      - main  # Se ejecuta en cada push a la rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          cd backend
          pip install -r requirements.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      
